using WebExpress.WebCore.WebAttribute;
using WebExpress.WebCore.WebInclude;

namespace WebExpress.WebUI.WebInclude
{
    /// <summary>
    /// Represents a collection of JavaScript resources to be included in a web application.
    /// </summary>
    /// <remarks>
    /// This class is used to define and manage the inclusion of JavaScript files required for the
    /// functionality of a web application.
    /// </remarks>
    [Asset("/assets/js/bootstrap.min.js")]
    [Asset("/assets/js/chart.js")]
    [Asset("/assets/js/popper.min.js")]
    [Asset("/assets/js/webexpress.webui.js")]
    [Asset("/assets/js/webexpress.webui.avatar.js")]
    [Asset("/assets/js/webexpress.webui.avatar.dropdown.js")]
    [Asset("/assets/js/webexpress.webui.button.js")]
    [Asset("/assets/js/webexpress.webui.button.split.toggle.js")]
    [Asset("/assets/js/webexpress.webui.chart.js")]
    [Asset("/assets/js/webexpress.webui.code.js")]
    [Asset("/assets/js/webexpress.webui.color.js")]
    [Asset("/assets/js/webexpress.webui.dashboard.js")]
    [Asset("/assets/js/webexpress.webui.date.js")]
    [Asset("/assets/js/webexpress.webui.dropdown.js")]
    [Asset("/assets/js/webexpress.webui.editor.js")]
    [Asset("/assets/js/webexpress.webui.expandable.js")]
    [Asset("/assets/js/webexpress.webui.filelist.js")]
    [Asset("/assets/js/webexpress.webui.frame.js")]
    [Asset("/assets/js/webexpress.webui.gameoflife.js")]
    [Asset("/assets/js/webexpress.webui.graph.viewer.js")]
    [Asset("/assets/js/webexpress.webui.graph.editor.js")]
    [Asset("/assets/js/webexpress.webui.input.avatar.js")]
    [Asset("/assets/js/webexpress.webui.input.calendar.js")]
    [Asset("/assets/js/webexpress.webui.input.cascading.js")]
    [Asset("/assets/js/webexpress.webui.input.color.js")]
    [Asset("/assets/js/webexpress.webui.input.date.js")]
    [Asset("/assets/js/webexpress.webui.input.move.js")]
    [Asset("/assets/js/webexpress.webui.input.rating.js")]
    [Asset("/assets/js/webexpress.webui.input.selection.js")]
    [Asset("/assets/js/webexpress.webui.input.tag.js")]
    [Asset("/assets/js/webexpress.webui.input.tile.js")]
    [Asset("/assets/js/webexpress.webui.kanban.js")]
    [Asset("/assets/js/webexpress.webui.list.js")]
    [Asset("/assets/js/webexpress.webui.login.js")]
    [Asset("/assets/js/webexpress.webui.modal.js")]
    [Asset("/assets/js/webexpress.webui.modal.page.js")]
    [Asset("/assets/js/webexpress.webui.modal.form.js")]
    [Asset("/assets/js/webexpress.webui.modal.confirm.js")]
    [Asset("/assets/js/webexpress.webui.modal.confirm.delete.js")]
    [Asset("/assets/js/webexpress.webui.modal.sidebar.panel.js")]
    [Asset("/assets/js/webexpress.webui.move.js")]
    [Asset("/assets/js/webexpress.webui.overflow.js")]
    [Asset("/assets/js/webexpress.webui.pagination.js")]
    [Asset("/assets/js/webexpress.webui.quickfilter.js")]
    [Asset("/assets/js/webexpress.webui.rating.js")]
    [Asset("/assets/js/webexpress.webui.responsive.js")]
    [Asset("/assets/js/webexpress.webui.search.js")]
    [Asset("/assets/js/webexpress.webui.search.content.js")]
    [Asset("/assets/js/webexpress.webui.selection.js")]
    [Asset("/assets/js/webexpress.webui.sidebar.js")]
    [Asset("/assets/js/webexpress.webui.smartedit.js")]
    [Asset("/assets/js/webexpress.webui.smartview.js")]
    [Asset("/assets/js/webexpress.webui.split.js")]
    [Asset("/assets/js/webexpress.webui.tab.js")]
    [Asset("/assets/js/webexpress.webui.table.js")]
    [Asset("/assets/js/webexpress.webui.table.reorderable.js")]
    [Asset("/assets/js/webexpress.webui.tag.js")]
    [Asset("/assets/js/webexpress.webui.tile.js")]
    [Asset("/assets/js/webexpress.webui.toolbar.js")]
    [Asset("/assets/js/webexpress.webui.tree.js")]
    [Asset("/assets/js/webexpress.webui.upload.js")]
    [Asset("/assets/js/webexpress.webui.view.js")]
    [Asset("/assets/js/editor/addons.js")]
    [Asset("/assets/js/editor/emojis.js")]
    [Asset("/assets/js/editor/formatting.js")]
    [Asset("/assets/js/editor/media.js")]
    [Asset("/assets/js/editor/table.js")]
    [Asset("/assets/js/editor/addons/default.js")]
    [Asset("/assets/js/editor/addons/gameoflife.js")]
    [Asset("/assets/js/i18n/en.js")]
    [Asset("/assets/js/i18n/de.js")]
    [Asset("/assets/js/templates/default.js")]
    [Asset("/assets/js/syntax/bash.js")]
    [Asset("/assets/js/syntax/basic.js")]
    [Asset("/assets/js/syntax/cmd.js")]
    [Asset("/assets/js/syntax/cobol.js")]
    [Asset("/assets/js/syntax/cpp.js")]
    [Asset("/assets/js/syntax/csharp.js")]
    [Asset("/assets/js/syntax/groovy.js")]
    [Asset("/assets/js/syntax/java.js")]
    [Asset("/assets/js/syntax/javascript.js")]
    [Asset("/assets/js/syntax/markdown.js")]
    [Asset("/assets/js/syntax/php.js")]
    [Asset("/assets/js/syntax/powershell.js")]
    [Asset("/assets/js/syntax/property.js")]
    [Asset("/assets/js/syntax/python.js")]
    [Asset("/assets/js/syntax/visualbasic.js")]
    [Asset("/assets/js/syntax/xml.js")]
    [Asset("/assets/js/panels/webexpress.webui.panel.editor.addon.js")]
    [Asset("/assets/js/panels/webexpress.webui.panel.editor.image.js")]
    [Asset("/assets/js/panels/webexpress.webui.panel.editor.link.js")]
    [Asset("/assets/js/panels/webexpress.webui.panel.table.columns.js")]
    [Asset("/assets/js/widgets/default.js")]
    public sealed class IncludeJavaScript : IInclude
    {

    }
}
