name: Generate and Deploy Preview Documentation

on:
  push:
    branches:
      - develop

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Add DocFX to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      
    - name: Clone WebExpress.WebCore
      run: |
        git clone --branch develop https://github.com/webexpress-framework/WebExpress.WebCore.git
        mkdir -p packages
        
    - name: Create wwwroot directory for WebCore
      run: mkdir -p WebExpress.WebCore/src/WebExpress.WebCore/wwwroot

    - name: Build WebExpress.WebCore
      run: |
        dotnet build WebExpress.WebCore/src/WebExpress.WebCore/WebExpress.WebCore.csproj -c Release

    - name: Pack WebExpress.WebCore
      run: |
        dotnet pack WebExpress.WebCore/src/WebExpress.WebCore/WebExpress.WebCore.csproj -c Release -o packages --no-build

    - name: Create nuget.config
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > nuget.config
        echo '<configuration>' >> nuget.config
        echo '  <packageSources>' >> nuget.config
        echo '    <add key="LocalPackages" value="packages" />' >> nuget.config
        echo '    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />' >> nuget.config
        echo '  </packageSources>' >> nuget.config
        echo '</configuration>' >> nuget.config

    - name: Debug list all .csproj files
      run: find . -name "*.csproj"

    - name: Restore packages with local feed
      run: dotnet restore ./src/WebExpress.WebUI/WebExpress.WebUI.csproj --configfile nuget.config

    - name: Build WebExpress.WebUI
      run: dotnet build ./src/WebExpress.WebUI/WebExpress.WebUI.csproj -c Release --no-restore

    - name: Create globalMetadata.json
      run: |
        echo '{ "_isPreview": true }' > docs/globalMetadata.json

    - name: Generate documentation
      run: |
        cd docs 
        docfx metadata
        docfx build -o _site/preview --globalMetadataFile globalMetadata.json

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
